# Generated by Django 2.2.7 on 2019-11-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=15, help_text='Latitude', max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=15, help_text='Longitude', max_digits=20)),
                ('unique_squirrel_id', models.CharField(help_text='Unique Squirrel ID', max_length=50)),
                ('shift', models.CharField(choices=[('am', 'AM'), ('am', 'PM')], default='am', help_text='Shift', max_length=3)),
            ],
        ),
    ]
