# Generated by Django 2.2.7 on 2019-11-27 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('ground_plane', 'Ground Plane'), ('above_ground', 'Above Ground')], default='ground_plane', help_text='Location', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='approahces',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Approaches', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='chasing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Chasing', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Climbing', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date'),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='eating',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Eating', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='foraging',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Foraging', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Indifferent', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Kuks', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Moans', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='other_activites',
            field=models.CharField(default='-', help_text='Other Activities', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('grey', 'Grey'), ('cinnamon', 'Cinnamon'), ('black', 'Black')], default='grey', help_text='Primary Fur Color', max_length=10),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Quaas', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='running',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Running', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Runs From', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default='-', help_text='Specific Location', max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Tail Flags', max_length=15),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], default='true', help_text='Tail Twitches', max_length=15),
        ),
    ]
