# Generated by Django 2.2.7 on 2019-11-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0003_auto_20191126_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(default='-', help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(default='-', help_text='Specific Location', max_length=100, null=True),
        ),
    ]
