# Generated by Django 2.2.7 on 2019-11-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0004_auto_20191126_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, default='-', help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, default='-', help_text='Specific Location', max_length=100, null=True),
        ),
    ]
