# Generated by Django 2.2.7 on 2019-11-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0006_auto_20191127_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Shift', max_length=3),
        ),
    ]
