# Generated by Django 2.2.7 on 2019-11-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0007_auto_20191127_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='Adult', help_text='Age', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Grey'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], default='Gray', help_text='Primary Fur Color', max_length=10),
        ),
    ]
