# Generated by Django 2.2.7 on 2019-11-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0009_auto_20191127_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=10),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Approaches', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Chasing', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Climbing', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(blank=True, help_text='Date', null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Eating', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Foraging', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Indifferent', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Kuks', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Moans', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='other_activities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Quaas', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Running', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Runs From', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Tail Flags', max_length=15),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twitches',
            field=models.CharField(choices=[('true', 'True'), ('false', 'False')], help_text='Tail Twitches', max_length=15),
        ),
    ]
