# Generated by Django 2.2.7 on 2019-11-27 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0010_auto_20191127_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 11, 27, 7, 41, 38, 151751, tzinfo=utc), help_text='Date'),
        ),
    ]
