# Generated by Django 2.2.7 on 2019-11-27 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0011_auto_20191127_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date'),
        ),
    ]
